name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: windows-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/native
          cargo build

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: mac-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/native
          cargo build

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: ubuntu-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Get dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: sudo apt install libasound2-dev libudev-dev pkg-config
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/native
          cargo build

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./launchers/wasm/dist
          key: wasm-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Install Trunk
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"
      - name: Trunk Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/wasm
          trunk build
