name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: cargo build

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: cargo build

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: sudo apt install libasound2-dev libudev-dev pkg-config
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: cargo build

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-wasm-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Trunk
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: jetli/trunk-action@v0.2.0
        with:
          version: "latest"
      - name: Trunk Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: trunk build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: sudo apt install libasound2-dev libudev-dev pkg-config
      - name: Pull Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-cargo-${{ hashFiles('**/Cargo.lock') }}
      # Unit testing
      - name: Test
        run: cargo test --workspace
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-lint-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: sudo apt install libasound2-dev libudev-dev pkg-config
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy 
          rustup component add rustfmt
      - name: cargo fmt
        run: |
          cargo fmt -- --check
      - name: cargo clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings  
